In [1]:
import pandas as pd

In [3]:
df_cc = pd.read_csv(r"data-augmentation-code_comments.csv")

In [4]:
df_cc.head()

                                                text             class
0  //TO DO : delete the file if it is not a valid...  requirement_debt
1  // TODO: Implement file deletion for invalid f...  requirement_debt
2  // TODO: Incorporate file elimination logic fo...  requirement_debt
3  /**\r\n * TODO:\r\n * comment field doesn't in...  requirement_debt
4  TODO: The comment field is still missing some ...  requirement_debt

In [6]:
df_cc["class"].value_counts()

class
non_debt              58204
documentation_debt     2701
test_debt              2635
requirement_debt       2271
Name: count, dtype: int64

In [7]:
df_cm = pd.read_csv(r"data-augmentation-commit-messages.csv")

In [8]:
df_cm.head()

                                                text     class
0  https://issues.apache.org/jira/browse/AMQ-3935...  non_debt
1                      Optimize in-men cube building  non_debt
2  GROOVY-5816 Add an "encoding" option for Groov...  non_debt
3  AMBARI-5596. Jobs page: Selection of vertex in...  non_debt
4  Bug 53145 - HTTP Sampler - function in path ev...  non_debt

In [9]:
df_cm["class"].value_counts()

class
non_debt              4253
test_debt              522
requirement_debt       513
documentation_debt     490
code_debt              422
design_debt            100
Name: count, dtype: int64

In [10]:
df_i = pd.read_csv(r"data-augmentation-issues.csv")

In [11]:
df_i.head()

                                                text     class
0                           If you use then it works  non_debt
1  If you use spring and then refer to an endpoin...  non_debt
2                   Using <to> with id and ref fails  non_debt
3             There is a basic health indicator now.  non_debt
4  We need the health check API in camel-core for...  non_debt

In [12]:
df_i["class"].value_counts()

class
non_debt              19904
requirement_debt       2134
test_debt              2028
documentation_debt     1948
code_debt              1232
design_debt             937
Name: count, dtype: int64

In [13]:
df_pr = pd.read_csv(r"data-augmentation-pull-requests.csv")

In [14]:
df_pr.head()

                                                text     class
0                         +1\r\nThanks @aokolnychyi!  non_debt
1  ekhacoop@ welcome to the Apache Fineract commu...  non_debt
2  Build Success with Spark 2.1.0, Please check C...  non_debt
3   Like setup, can probably do without the comments  non_debt
4  can you change these params to `maxFailedTasks...  non_debt

In [15]:
df_pr["class"].value_counts()

class
non_debt              4282
documentation_debt     504
requirement_debt       500
test_debt              476
code_debt              417
design_debt             93
Name: count, dtype: int64

In [28]:
# df_cc = df_cc[["text", "classification"]]
# df_cm = df_cm[["text", "classification"]]
# df_i = df_i[["text", "classification"]]
# df_pr = df_pr[["text", "classification"]]

df_cc.rename(columns={ "label": "class"}, inplace=True)
df_cm.rename(columns={ "label": "class"}, inplace=True)
df_i.rename(columns={ "label": "class"}, inplace=True)
df_pr.rename(columns={ "label": "class"}, inplace=True)

In [34]:
df_cc.to_csv("data-augmentation-code_comments.csv", index=False)
df_cm.to_csv("data-augmentation-commit-messages.csv", index=False)
df_i.to_csv("data-augmentation-issues.csv", index=False)
df_pr.to_csv("data-augmentation-pull-requests.csv", index=False)

In [16]:
df_cc["class"].value_counts()

class
non_debt              58204
documentation_debt     2701
test_debt              2635
requirement_debt       2271
Name: count, dtype: int64

In [17]:
df_cc = df_cc[df_cc["class"] != "code/design_debt"]

In [18]:
df_merged = pd.concat([df_cc, df_cm, df_i, df_pr], ignore_index=True)

In [19]:
df_merged["class"].value_counts()

class
non_debt              86643
test_debt              5661
documentation_debt     5643
requirement_debt       5418
code_debt              2071
design_debt            1130
Name: count, dtype: int64

In [20]:
df_merged.to_csv("data-augmentation-merged.csv", index=False)